server:
  port: 6070


spring:
 application:
   name: CustomerService
 jpa:
  database: MYSQL
  show-sql: true
  generate-ddl: false
  
 datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://root:password@localhost:3306/omscustomerdb?reconnect=true
    username: root
    password: password
    hikari:
      connectionTimeout : 30000
      idleTimeout : 600000
      maxLifetime : 1800000
      maximumPoolSize : 5

 rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
 cloud:
  stream:
   default: 
    contentType: application/json
   bindings:
     customerCreatedChannel:
       destination: CustomerCreatedExchange
       group: CustomerCreatedMQ
         
   
